### ISSUE TITLE
Investigate TypsyRyde and decide if Web Jam LLC should take them on as a client

### ISSUE THREAD

**Issue by JoshuaVSherman** [Web-Jam-Salem-Business/Web-Jam-Business#135]
* Call Lisa, give her an update on our business status, solidify her problem statement, and schedule a meeting for Thursday to discuss pricing options  **DONE**

**Comment by chemmom2** [comment]
I took a quick look at the document and highlighted the parts that looked
like they were relevant to the app.

**Comment by JoshuaVSherman** [comment]
@chemmom2 Maria is the best

**Comment by JoshuaVSherman** [comment]
https://docs.google.com/document/d/1-swlxTbSlmbGkOIgaYn-BrrFwd3b1UCkDDfUX9rOqq8/edit#
