### ISSUE TITLE
Get Lisa to agree to option 2

### ISSUE THREAD

**Issue by JoshuaVSherman** [Web-Jam-Salem-Business/Web-Jam-Business#158]
* Option 1, keeping her current web infra, we start with an investigation period costing x dollars (use Adam's email as a skeleton for calculations, don't forget time it will take coordinating with Lisa on gaining access to the infra and/or time coordinating with the India developer person, also it being a combination of Java, PHP, and Iphone technologies (all of which are foreign to Josh, this means contracting out to other developer resources = less profits or increased time for Josh to spin up on development environments, infra, and tools to work with those technologies)
* Option 2, She invests in Jam Cab upfront on a weekly basis and gets a version of the app that is re-branded to be Tipsy Ryde when completed (we would need to determine cost and time estimates for this proposal)
* Option 3, She does not invest in Jam Cab, and we develop the app, and when it is completed, she is given the opportunity to purchase it from us to be rebranded for Tipsy Ryde (we would need to have a potential purchase price and time frame for this to be completed)

@LinuxBozo any opinions on this initial though here?

**Comment by JoshuaVSherman** [comment]
@chemmom2 @LinuxBozo 

Lisa is interested in option 2 (which is the option I wanted), so the next step here is to come up with a phased approach with some time estimates based on the amount per week that she is willing to invest

**Comment by LinuxBozo** [comment]
I wouldn't have presented any option without figuring out exactly what she needs, but hey, that's just me. Also, Option 2, "invest" has legal connotations. Who owns the product in the end?  What's the split? What does the profit structure look like? Dividends?

**Comment by JoshuaVSherman** [comment]
@LinuxBozo @chemmom2 
our product is open source, she owns her branding, she would own her data - we would need to figure out some legalieze for that - good point
We would need her to agree that we are provides services
We can reuse these features in other apps or even rebrand the ride share cab app for another business if they are willing to pay us to do that
The state of NC legal document describes here "needs"
she is willing to throw away her current JAVA, PHP, Iphone - code because I'm not willing to ramp up on that tech stack
