### ISSUE TITLE
complete a first draft of marketing fact sheet for the business

### ISSUE THREAD

**Issue by JoshuaVSherman** [Web-Jam-Salem-Business/Web-Jam-Business#195]
https://docs.google.com/document/d/1KucbkLTURps7307cdZonAsuZo55CT0Z-no8s-XSiJzY/edit#

https://drive.google.com/open?id=1Sbn-rF-vE9IoJ4uEixRyRzvAcTBn9e-CnDMv1TiyO8c

https://drive.google.com/open?id=1mOY2QcMHJ0f_lX2GqfZLdvm78bMtwjK-oS4iUorhNKA

**Comment by JoshuaVSherman** [comment]
@LinuxBozo @chemmom2 https://docs.google.com/document/d/1KucbkLTURps7307cdZonAsuZo55CT0Z-no8s-XSiJzY/edit#
please review and provide any feedback if you can, thanks

**Comment by LinuxBozo** [comment]
Fact sheet focuses too much on the tech that customers don't know or care about.
Most aren't going to know what Mongo or ESNext are, nor things like CircleCI or Heroku. Yank them, and replace with things like:
 - Using modern agile development languages
 - automated testing and deployments
 - commodity cloud hosting
etc...
